const express = require('express')
const app = express();
const base64Img = require('base64-img');
const port = 4000;

app.get('/', function (req, res) {
  res.send('Hello World!')
})

var bodyParser = require('body-parser')

app.use(function(req, res, next) {
    res.header('Access-Control-Allow-Origin', "*");
    res.header('Access-Control-Allow-Methods','GET,PUT,POST,DELETE');
    res.header('Access-Control-Allow-Headers', 'Content-Type');
    next();
})

app.get("/api/id/:w", function(req, res) { 
    // var data = getIcon(req.params.w); 
    // var fs = require('fs');
    // string generated by canvas.toDataURL()
    // console.log(req);
    var img = req.params.w;

    console.log(img)
    // strip off the data: url prefix to get just the base64-encoded bytes
    // var data = img.replace(/^data:image\/\w+;base64,/, "");
    // var img = new Buffer(data, 'base64'); 
    // res.writeHead(200, { 'Content-Type': 'image/png', 'Content-Length': img.length }); 
    // res.send(img); 
    res.send(`<img src=${decodeURI(img)} />`);
});

app.listen(port, function () {
  console.log(`Example app listening on port ${port}!`)
})
